[
  {
    "timestamp": "2025-04-21T16:01:36.579954",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-21T16:05:04.953525",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-22T10:16:55.325125",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-22T10:19:36.468860",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-22T10:21:40.446502",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-22T10:23:44.141814",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-22T10:27:39.425478",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-22T11:40:03.030642",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-22T11:41:30.675746",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-22T13:20:00.938978",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-22T13:21:07.851587",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-22T13:23:35.646270",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-22T16:42:21.442408",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T14:26:07.719368",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T14:26:54.279590",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T14:34:22.575581",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T15:32:33.153321",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T17:56:58.555245",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T17:57:53.499716",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T17:58:23.264884",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T18:04:28.245143",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T18:04:56.101609",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T18:08:00.508860",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T18:09:53.433095",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T18:36:11.628323",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T18:39:17.330554",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T18:39:39.342395",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-25T18:41:46.538326",
    "source": "tennisexplorer.com",
    "error": "Connection failed 3 times"
  },
  {
    "timestamp": "2025-04-26T08:23:44.299580",
    "source": "fetch_current_top30players",
    "error": "Traceback (most recent call last):\n  File \"c:\\Python\\Python311\\20230608\\tennis_web\\ATP_from_blog_git.py\", line 177, in fetch_current_top30players\n    points = int(cols[3].text.strip().replace(\",\", \"\"))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nValueError: invalid literal for int() with base 10: '2001-08-16'\n"
  }
]